version: '3.9'

services:
  web:
    build:
      context: ./ReserveEase.Web
    container_name: project
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=${SERVER_IP};port=3306;database=${DB_NAME};uid=${USER_ID};pwd=${DB_PASSWORD}
    networks:
      - reserveease-network

networks:
  reserveease-network:
    driver: bridge